### PR TITLE
Merge the latest changes from the main Klipper codebase.

### PR DESCRIPTION
**Pull request by bsas**

### CODE REVIEW

**Comment by SteveGotthardt** [comment]
The FLASH_START in Kconfig has been changed to be FLASH_BOOT_ADDRESS
That is why test is failing. Since you started PR can you update hd32 Kconfig please?
thanks
details of what was changed here: https://github.com/Klipper3d/klipper/commit/42e9adcfc9963b54c71e8851e1a6a41a001531e5

**Comment by bsas** [comment]
Done but still fails somewhere else...

**Comment by SteveGotthardt** [comment]
Sorry, it looks like the FLASH_BOOT_ADDRESS is an addition - the FLASH_START needs to remain as it was and add something from this commit:
https://github.com/Klipper3d/klipper/commit/42e9adcfc9963b54c71e8851e1a6a41a001531e5#diff-ddc628c25309448e67d337fc23f65707a18bd9efa78dbafedb6ede6cd2005643

config FLASH_BOOT_ADDRESS
    hex
    default 0x0

From here it looks like 0x0 is correct: https://wiki.segger.com/HDSC_HC32F460

**Comment by bsas** [comment]
Done.

**Pull request merged**
